# Generated by Django 5.0.1 on 2024-01-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_client_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
