# Generated by Django 5.0.1 on 2024-01-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cooperative_balances_cards_devices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Card',
        ),
    ]
