# Generated by Django 5.0.1 on 2024-01-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_balances_balance_rename_devices_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='user_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
