# Generated by Django 5.0.1 on 2024-01-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_subscription_subscriptiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='subscription_name',
            field=models.CharField(default='აბონემენტი', max_length=50),
        ),
    ]
