# Generated by Django 5.0.1 on 2024-01-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_device_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('timestamp', models.CharField(max_length=250)),
                ('pin', models.IntegerField()),
                ('card', models.CharField(max_length=50)),
                ('door', models.IntegerField()),
                ('event_type', models.IntegerField()),
                ('entry_exit', models.CharField(max_length=50)),
            ],
        ),
    ]
