# Generated by Django 5.0.1 on 2024-01-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_deviceevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceevent',
            name='card',
            field=models.CharField(max_length=20),
        ),
    ]
