# Generated by Django 5.0.1 on 2024-01-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_deviceevent_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceevent',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
