# Generated by Django 5.0.1 on 2024-02-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_card_card_number_alter_card_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceevent',
            name='payed',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
