# Generated by Django 5.0.1 on 2024-02-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_deviceevent_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='cooperative_device_price',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=10),
        ),
    ]
