# Generated by Django 5.0.1 on 2024-02-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_client_allowed_cooperatives'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionObserverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20)),
                ('cooperative_id', models.IntegerField()),
                ('operation_to_do', models.CharField(max_length=50)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
