# Generated by Django 5.0.1 on 2024-02-11 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_balance_user_alter_card_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceObserverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20)),
                ('operation_to_do', models.CharField(max_length=50)),
                ('processed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('allowed_cooperatives', models.ManyToManyField(related_name='balance_logs', to='users.cooperative')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
