# Generated by Django 5.0.1 on 2024-02-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_balanceobserverlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='user_balance_delta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
