# Generated by Django 5.0.1 on 2024-02-11 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_balance_user_balance_delta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanceobserverlog',
            name='allowed_cooperatives',
        ),
    ]
