# Generated by Django 5.0.1 on 2024-02-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_subsobserverlog_delete_subscriptionobserverlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='price',
        ),
    ]
