# Generated by Django 5.0.1 on 2024-02-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_device_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
