# Generated by Django 5.0.1 on 2024-02-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_client_sms_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
