# Generated by Django 5.0.1 on 2024-02-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_device_is_connected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_connected',
        ),
    ]
