# Generated by Django 5.0.1 on 2024-03-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_rename_timestamp_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Transaction_id',
            field=models.CharField(default='transaction', max_length=200),
        ),
    ]
