# Generated by Django 5.0.1 on 2024-03-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_card_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='temp',
            field=models.BooleanField(default=False),
        ),
    ]
