# Generated by Django 5.0.1 on 2024-03-12 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_card_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
