# Generated by Django 5.0.1 on 2024-03-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_cooperativeexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativeexpense',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
