# Generated by Django 5.0.1 on 2024-03-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_cooperativeexpense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='head',
            field=models.BooleanField(default=False),
        ),
    ]
