# Generated by Django 5.0.1 on 2024-03-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_client_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativeexpense',
            name='date',
            field=models.DateField(),
        ),
    ]
