# Generated by Django 5.0.1 on 2024-03-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_cooperativeexpense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='for_mobile',
            field=models.CharField(default='null', max_length=15),
        ),
        migrations.AddField(
            model_name='card',
            name='life_hours',
            field=models.CharField(default='null', max_length=15),
        ),
    ]
