# Generated by Django 5.0.1 on 2024-03-18 17:14

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_card_for_mobile_card_life_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativeexpense',
            name='date',
            field=users.models.MonthYearField(),
        ),
    ]
