# Generated by Django 5.0.1 on 2024-03-29 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_card_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceevent',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='device_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
