# Generated by Django 5.0.1 on 2024-03-29 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_deviceevent_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedCoopObserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative', models.CharField(max_length=50)),
                ('operation_to_do', models.CharField(max_length=50)),
                ('processed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_cooperative_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
