# Generated by Django 5.0.1 on 2024-04-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_subscription_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=250)),
            ],
        ),
    ]
